export async function GET() {
  return Response.json({

    "accountAssociation": {
      "header": "eyJmaWQiOi0xLCJ0eXBlIjoiYXV0aCIsImtleSI6IjB4NDk0NTIxQjdENDY1QTE1QjhGMzE0MzFkYWZkRjRBMEQ5MmUzZmRlZSJ9",
      "payload": "eyJkb21haW4iOiJiYXNlLXdyYXBwZWQyNS52ZXJjZWwuYXBwIn0",
      "signature": "AAAAAAAAAAAAAAAAyhG94Fl3s2MRZwKIYr4qFzl2yhEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAiSCrVbLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAul7REO_bo9AFv8iC11NYrLu4WEIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASQ_-6NvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAn78bHm7ZmwK6tT8oeB2ktsY-FD0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAPhSELIcxQMC9He6VmhtIBncm2etAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBdlRaxY2rRi9WHepzm8K0zVafW2sI3jL_vyNlKs6FKldcaha2dPF4NbVr-wOHx0IO_VmVnJ-3TrGkDOjs9osgChsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJJkkmSSZJI"

    },
    miniapp: {
      version: "1",
      name: "Base Wrapped",
      subtitle: "Your onchain year on Base",
      description: "Unwrap your Base activity into a beautiful shareable receipt.",
      homeUrl: "https://base-wrapped25.vercel.app",
      iconUrl: "https://base-wrapped25.vercel.app/icon.png",
      splashImageUrl: "https://base-wrapped25.vercel.app/splash.png",
      splashBackgroundColor: "#020617",
      primaryCategory: "finance",
      tags: ["base", "wrapped", "onchain"],
      heroImageUrl: "https://base-wrapped25.vercel.app/og.png",
      ogTitle: "Base Wrapped 2025",
      ogDescription: "See your onchain story on Base.",
      ogImageUrl: "https://base-wrapped25.vercel.app/og.png",
      noindex: false
    }
  });
}
